In [ ]:
class students:
    def __init__(self):
        self.student=[]
    def addstudent(self,name,regno):
        self.student.append({
            "Name":name,
            "reg no":regno
        })
    def listAllStudent(self):
        print(self.student)

    def searchStudent(self,name):
        pass
    def removestudent(self,name):
        pass
    def __str__(self):
        pass 



In [3]:
n=int(input("enter a number"))
i=1
while i<11:
      print(n,'*',i,'=',n * i)
      i+=1



12 * 1 = 12
12 * 2 = 24
12 * 3 = 36
12 * 4 = 48
12 * 5 = 60
12 * 6 = 72
12 * 7 = 84
12 * 8 = 96
12 * 9 = 108
12 * 10 = 120


In [1]:
#print 1 to 10 numbers
n = 1
for i in range (1,11):
    print(i)
    i = i+1

1
2
3
4
5
6
7
8
9
10


In [ ]:
#even numbers in reverse order


In [6]:
a =[1,2,3,
    4,5,6,
    7,8,9]
print(a)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
#
sum =0
list=[1,2,3,4,5]
for i in list:
    i=i+1

In [13]:
for i in range(1,11):
    for j in range(1,11):
        if(i==1) or (i+j==11):
            print("@",end=" ")
        else:
            print(" ",end=" ")    
    print()        

@ @ @ @ @ @ @ @ @ @ 
                @   
              @     
            @       
          @         
        @           
      @             
    @               
  @                 
@                   


In [20]:
for i in range(1,11):
    for j in range(1,11):
        if(i==1) or (i==10) or (j==1) or (j==10):
            print("@",end= " ")
        else:
            print(" ",end= " ")    
    print()  

@ @ @ @ @ @ @ @ @ @ 
@                 @ 
@                 @ 
@                 @ 
@                 @ 
@                 @ 
@                 @ 
@                 @ 
@                 @ 
@ @ @ @ @ @ @ @ @ @ 


In [23]:
for i in range(1,11):
    for j in range(1,11):
            print("@",end=" ")
    
    print()  

@ @ @ @ @ @ @ @ @ @ 
@ @ @ @ @ @ @ @ @ @ 
@ @ @ @ @ @ @ @ @ @ 
@ @ @ @ @ @ @ @ @ @ 
@ @ @ @ @ @ @ @ @ @ 
@ @ @ @ @ @ @ @ @ @ 
@ @ @ @ @ @ @ @ @ @ 
@ @ @ @ @ @ @ @ @ @ 
@ @ @ @ @ @ @ @ @ @ 
@ @ @ @ @ @ @ @ @ @ 


In [24]:
def printRec(x):
     if x ==0:
          return

     printRec(x-1)
     print(x)

printRec(4)     

1
2
3
4


In [25]:
def printRec(x):
     if x ==0:
          return

     printRec(x-1)
     print(x)
     printRec(x-1)


printRec(3)     

1
2
1
3
1
2
1


In [1]:
for i in range(1,11):
    for j in range(1,11):
            print("-",end=" ")
    
    print()  

- - - - - - - - - - 
- - - - - - - - - - 
- - - - - - - - - - 
- - - - - - - - - - 
- - - - - - - - - - 
- - - - - - - - - - 
- - - - - - - - - - 
- - - - - - - - - - 
- - - - - - - - - - 
- - - - - - - - - - 


In [21]:
from numpy import *

arrl = array([
                 [1,2,3],
                [4,5,6],
                [7,8,9]   
    
            ])

print(arrl)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
